#!/bin/busybox sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

# Mount the root filesystem.
mount /dev/vda /mnt/root

# Clean up.
umount /proc
umount /sys
umount /dev

echo "That's it for init!"
# Boot the real thing.
exec switch_root /mnt/root /sbin/init
